#!/bin/bash

echo "================================================"
echo "🚀 COMPLETE SETUP - Email Verification Ready"
echo "================================================"
echo ""
echo "Your blogging application is now configured with:"
echo "✅ Flyway database migrations"
echo "✅ Automatic role initialization"
echo "✅ Email verification with MailTrap"
echo "✅ JWT authentication"
echo ""
echo "================================================"
echo "FOLLOW THESE STEPS TO RUN YOUR APP:"
echo "================================================"
echo ""
echo "Step 1: Ensure PostgreSQL is running on localhost:5432"
echo ""
echo "Step 2: Make sure database 'my_pq_db' is empty or recreated"
echo ""
echo "Step 3: Run the application"
echo "   cd /Users/gabrielcarauleanu/Desktop/web-application/backend"
echo "   mvn spring-boot:run"
echo ""
echo "Step 4: Wait for startup - you should see:"
echo "   ✅ Flyway migrations applied"
echo "   ✅ Roles inserted (ROLE_ADMIN, ROLE_WRITER, ROLE_VIEWER)"
echo "   ✅ Application started on port 8080"
echo ""
echo "Step 5: Test the API"
echo ""
echo "   Register user:"
echo "   curl -X POST http://localhost:8080/api/auth/register \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"username\": \"testuser\", \"email\": \"test@example.com\", \"password\": \"Test123456\"}'"
echo ""
echo "   Check MailTrap for verification email"
echo ""
echo "   Verify email (replace TOKEN with actual token):"
echo "   curl 'http://localhost:8080/api/auth/verify-email?token=TOKEN'"
echo ""
echo "   Login:"
echo "   curl -X POST http://localhost:8080/api/auth/login \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"username\": \"testuser\", \"password\": \"Test123456\"}'"
echo ""
echo "================================================"
echo "🎉 ALL CONFIGURATIONS COMPLETE"
echo "================================================"

