spring.application.name=demo

# DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/my_pq_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=admin

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true

spring.flyway.enabled=false

# JWT Configuration
app.jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkeymysecretkeymysecretmysecretkey
app.jwt.expiration=2592000000

# Admin Configuration
app.admin.register.code=282828282

# mailTrap Configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=b17ef51fdbf0cb
spring.mail.password=98bc86e34d6f1d
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.from=gabrielvalentine738@gmail.com

# email Verification
app.email.verification.expiration=86400000
app.frontend.url=http://localhost:3000/verify-email